// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Zagrean_Robert_project.Data;

namespace Zagrean_Robert_project.Migrations
{
    [DbContext(typeof(SuplimenteContext))]
    [Migration("20210110175606_FirstMigration")]
    partial class FirstMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Zagrean_Robert_project.Models.Client", b =>
                {
                    b.Property<int>("ClientID")
                        .HasColumnType("int");

                    b.Property<string>("Adresa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DataNasterii")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nume")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ClientID");

                    b.ToTable("Client");
                });

            modelBuilder.Entity("Zagrean_Robert_project.Models.Comenzi", b =>
                {
                    b.Property<int>("ComenziID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ClientID")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataComanda")
                        .HasColumnType("datetime2");

                    b.Property<int>("SuplimentID")
                        .HasColumnType("int");

                    b.Property<int?>("SuplimenteID")
                        .HasColumnType("int");

                    b.HasKey("ComenziID");

                    b.HasIndex("ClientID");

                    b.HasIndex("SuplimenteID");

                    b.ToTable("Comanda");
                });

            modelBuilder.Entity("Zagrean_Robert_project.Models.PublishedSuplements", b =>
                {
                    b.Property<int>("SuplementeID")
                        .HasColumnType("int");

                    b.Property<int>("PublisherID")
                        .HasColumnType("int");

                    b.Property<int?>("SuplimenteID")
                        .HasColumnType("int");

                    b.HasKey("SuplementeID", "PublisherID");

                    b.HasIndex("PublisherID");

                    b.HasIndex("SuplimenteID");

                    b.ToTable("Suplimente distribuite");
                });

            modelBuilder.Entity("Zagrean_Robert_project.Models.Publisher", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Adresa")
                        .HasColumnType("nvarchar(70)")
                        .HasMaxLength(70);

                    b.Property<string>("PublisherName")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.HasKey("ID");

                    b.ToTable("Distribuitor");
                });

            modelBuilder.Entity("Zagrean_Robert_project.Models.Suplimente", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("Pret")
                        .HasColumnType("decimal(6, 2)");

                    b.Property<string>("Producator")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tip")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Supliment");
                });

            modelBuilder.Entity("Zagrean_Robert_project.Models.Comenzi", b =>
                {
                    b.HasOne("Zagrean_Robert_project.Models.Client", "Client")
                        .WithMany("Comenzis")
                        .HasForeignKey("ClientID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Zagrean_Robert_project.Models.Suplimente", "Suplimente")
                        .WithMany("Comenzis")
                        .HasForeignKey("SuplimenteID");
                });

            modelBuilder.Entity("Zagrean_Robert_project.Models.PublishedSuplements", b =>
                {
                    b.HasOne("Zagrean_Robert_project.Models.Publisher", "Publisher")
                        .WithMany("PublishedSuplements")
                        .HasForeignKey("PublisherID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Zagrean_Robert_project.Models.Suplimente", "Suplimente")
                        .WithMany("PublishedSuplements")
                        .HasForeignKey("SuplimenteID");
                });
#pragma warning restore 612, 618
        }
    }
}
